# Filled with normalized source fingerprints for the supported native v1 ABI.
include("${CMAKE_CURRENT_LIST_DIR}/SimexProtocolLock.cmake")
foreach(entry IN LISTS JEV_SIMEX_PROTOCOL_LOCK)
    string(REPLACE "=" ";" pair "${entry}")
    list(GET pair 0 path)
    list(GET pair 1 expected)
    set(full_path "${JEV_SIMEX_SOURCE_DIR}/src/${path}")
    if(NOT EXISTS "${full_path}")
        message(FATAL_ERROR "Missing simex protocol header: ${full_path}")
    endif()
    file(READ "${full_path}" source)
    string(REPLACE "\r\n" "\n" source "${source}")
    string(SHA256 actual "${source}")
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Simex protocol drift in ${path}. Review compatibility before updating cmake/SimexProtocolLock.cmake.")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${full_path}")
endforeach()
